server :
  port    : 1000
databaseMaster : 
  address : "localhost"
  db      : "db_mall_tangsel"
  user    : "jemmycalak"
  password: "jemmycalak"
databaseSlave : 
  address : "localhost"
  db      : "db_mall_tangsel_backup"
  user    : "jemmycalak"
  password: "jemmycalak"
redis :
  address : "localhost:6437"
